# this is the name of this skillet, should be unique within a given repository
name: vsphere_single_pavm

# label should be a human readable label that conveys what this skillet will do
label: Deploying Single Pan-OS VM-Series on vSphere Environment.

# description is a longer more informative version of a label
description: vSphere Single Pan-OS VM-Series

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  collection:
    - Datacenter Virtualization


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: vsphere_server
    description: vCenter IP or FQDN
    default: 10.197.140.102
    type_hint: text
  - name: user
    description: vCenter username
    default: ansible@panlab.local
    type_hint: text
  - name: password
    description: vCenter Password
    default:
    type_hint: password
  - name: vsphere_datacenter
    description: vCenter Datacenter name
    default: PanLab
    type_hint: text
  - name: vsphere_vm_folder
    description: Folder Name to host the PA-VM
    default: terraform-pa-vm-01
    type_hint: text
  - name: vsphere_vm_name
    description: VM name
    default: pa-vm-01
    type_hint: text
  - name: vsphere_vm_template
    description: PA-VM template name
    default: pavmvnf-8.1.2
    type_hint: text
  - name: vsphere_cluster
    description: vCenter Cluster name
    default: Cluster_others
    type_hint: text
  - name: vsphere_datastore
    description: vCenter datastore
    default: DS_Local_OpenStack
    type_hint: text
  - name: vsphere_vcpu_number
    description: Number of vCPU cores
    default: 2
    type_hint: dropdown
    dd_list:
      - key: 2
        value: 2
      - key: 4
        value: 4
      - key: 8
        value: 8
      - key: 16
        value: 16
  - name: vsphere_memory_size
    description: Memory size
    default: 4608
    type_hint: dropdown
    dd_list:
      - key: 4608
        value: 4608
      - key: 6656
        value: 6656
      - key: 9216
        value: 9216
      - key: 16384
        value: 16384
      - key: 57344
        value: 57344
  - name: vsphere_port_group_mgmt
    description: Manavgement Port Group
    default: "VM Network"
    type_hint: text
  - name: vsphere_port_group_untrust
    description: Untrust Port Group
    default: "VM Network"
    type_hint: text
  - name: vsphere_port_group_trust
    description: Trust Port Group
    default: "VM Network"
    type_hint: text
  - name: pavm_hostname
    description: VM-Series Host name
    default: PAN_NGFW_VNF
    type_hint: text
  - name: pavm_ip_address
    description: VM-Series Management IP address
    default: 192.168.55.10
    type_hint: text
  - name: pavm_netmask
    description: VM-Series Management netmask
    default: 255.255.255.0
    type_hint: text
  - name: pavm_gateway
    description: VM-Series Management default gateway
    default: 192.168.55.1
    type_hint: text
  - name: pavm_dns_primary
    description: VM-Series Management Primary DNS
    default: 8.8.8.8
    type_hint: text
  - name: pavm_dns_secondary
    description: VM-Series Management Secondary DNS
    default: 4.2.2.2
    type_hint: text
  - name: panorama_server_ip
    description: Panorama Server IP
    default: xxxxxxx
    type_hint: text
  - name: panorama_tplname
    description: Panorama Template Name
    default: VNF-Template-Stack
    type_hint: text
  - name: panorama_dgname
    description: Panorama Device Group Name
    default: VNF-DG
    type_hint: text
  - name: panorama_vm_auth_key
    description: Panorama VM Auth Key
    default: xxxxxxxxxxxxx
    type_hint: text
  - name: pavm_authcode
    description: VM-Series Licensing Authcode
    default: xxxxxxx
    type_hint: text